version: '3.8'

services:
  gamestore-api:
    image: gamestore-api
    build:
      context: .
      dockerfile: src/GameStore.API/Dockerfile
    ports:
      - "8081:5000"
      - "8080:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: game_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres-data:
  redis-data:
